export const categories = [
	'Music',
	'Art',
	'Film',
	'Theater',
	'Sports',
	'Technology',
	'Business',
	'Education',
	'Health & Wellness',
	'Food & Drink',
	'Networking',
	'Charity',
	'Fashion',
	'Dance',
	'Comedy',
	'Literature',
	'Gaming',
	'Photography',
	'Crafts & DIY',
	'Science',
	'Adventure',
	'Pets & Animals',
	'History',
	'Culture',
	'Spirituality',
	'Community',
	'Career Development',
	'Nature & Outdoors',
	'Travel',
	'Workshops',
	'Startup',
	'Parenting & Family',
	'Real Estate',
	'Investment',
	'Social Impact',
	'Environment',
];
